---
title: "article-outline"
format: html
---

Reverse Outline

Main Thesis: "Examining the past 100 years of graphical testing, we summarize best practices for creating effective graphics and discuss what the future holds for graphics and empirical testing of interactive statistical visualizations."

Design of Statistical Graphics

|"Charts and graphs are used for many purposes: to summarize data; for analysis, exploration, and discovery;. . ."|This sentence helps set up the audience for how charts and graphs are used, giving a basis for how the main thesis is to be explored.|

|"The distinction between infographics and statistical graphics is primarily one of intent:. . ."|Here, two types of graphics are introduced and we know they are to be compared/contrasted. This will help with the "best practices" discussion in the thesis.

|This paragraph doesn't seem to have a main point. It gives example graphics and how they're used, but doesn't have a single sentence that really relates to the thesis. |Explaining the graphs does give examples of "effective graphics" which can be beneficial to the audience.|

1.2 Statistical Mapping Using a Grammar of Graphics (Paragraphs 1&2 and 3&4 combined)

|"The classifications of graphics. . . provide an elegant framework for comparing different types of graphical representations. . ."|How you talk about and classify graphics can help statisticians understand which graphics are similar to each other and determine new ways to present information.|

|"Using the grammar of graphics, it is easy for experimenters to compare different types of charts using the same data. . ."|These paragraphs discuss how the grammar of graphics has been/is being used and how it is beneficial to statisticians using graphics.|

Testing Methods

2.1 Explicitly Structured Graphical Tests

|". . . as a result, most of the testing methods we discuss are focused on the attentive portion of the perceptual process."|This is mostly an introductory paragraph, so this doesn't help to support the thesis. However, it does introduce one of the "tests" mentioned.|

2.1.1 - Preattentive Graph Perception (entire subsection)

|"While these displays may not follow best graphical practice in other respects, they do show the utility of designing with the preattentive perceptual process in mind.|This section explains the importance of graph perception and how it can be used to improve graphs.|

2.1.2 Attention mediated testing methods

|Another introductory paragraph|This sets up more experimentation on the "overall performance of different graphical forms."|

2.1.2.1 Direct observation: numerical estimation, speed, and error rates

|"The accuracy of various types of charts. . . is then used to determine which charts are superior."|Giving an exact experimental method like they did in this paragraph helps support the thesis "summarize best practices. . ." It gives examples of how one graph is determined to be better than another.|

|"There are limits tow hat one can test using direct estimation. . ."|This paragraph explains the limitations of these experiments and mentions how we may be able to get around them in future testing.|

2.1.2.2 Psychophysics and signal detection theory

|"Psychophysical experimental design is focused on whether an effect is detectable and whether the magnitude of the effect can be accurately estimated."|This one also doesn't have a huge support of the thesis, but it does explain another experiment type for determining graph effectiveness.|

2.1.2.3 Thinking aloud

|"The think aloud process allows experimenters to examine the use of complex graphics in the wild,. . . "|Using this method, researchers can now test "real-world" situations and how different visualizations fare. This method gives more information and can be helpful for future graphical improvements.

2.1.2.4 Eye Tracking

|"The use of eye tracking. . . allows researchers to understand how dyslexia and graph literacy affect the graph comprehension process, providing better design guidelines. . ."|This method can improve the accessibility of all graphs, especially if this research is implemented consistently in future statistical publications.|

2.1.2.5 Combination experiments

|". . .but when these techniques are combined, they provide a much more complete picture of the cognitive processes that underlie graphical perception."|Like so many sections before, this is an example of how designed experiments can help improve graphics to be more understandable.|

2.2 Implicit Graphical Tests Using Visual Inference

|I didn't really see one line that worked as the main idea.|This is another example of an experiment ran by researchers, this time comparing randomly generated graphs with an original. If the original can be easily picked out, we find that there seems to be a pattern to make it stick out. Can do this experiment with different types of charts to see if one has a better chance of having the real chart chosen.|

|". . .when comparing a model generating clustered data to a model generating data with linear. . . color and shape aesthetics slightly increase likelihood. . ."|Changing different aesthetics of the graph can slightly change how it is interpreted by the audience.|

Current best graphical practice

3.1 Cognitive Principles

|"good graphics take advantage of the human visual system's ability to process large amounts of visual information with relatively little effort."|When data visualization is done well, it can be a very helpful tool and should be studied more thoroughly.|

3.1.1 Proximity

|"Proximity is used to place items to compare close together, and less important comparisons further apart.|

3.1.2 Similarity

|"we group things that have similar appearances and exclude objects with different appearances"|

3.1.3 Common Region

|"elements contained within a common region belong together"|

3.1.4 Common Fate

|". . . tendency to group objects that are moving together in the same direction and at the same speed together. "|

3.1.5 Working Memory

|"categorical scales with more than seven categories decrease readability. . ."|

3.1.6 Change Blindness

|". . . it is difficult to identify changes between similar scenes."|

|The six sections above all detail common practices in making "good visualizations" today. They explain human tendencies and how statisticians can use graphs to easily share important information.|

3.1.7 Ease of Comparisons

|"This ranking of cognitive tasks provides some consistent guidance for chart design:"|This section gives an ordered list for importance in creating a good graph. This is really helpful for making sure all information is efficiently displayed.|

3.2 Chart Design

|"use of redundant aesthetics. . . results in higher identification of corresponding data features."|Obviously creating charts that are easier to understand and distinguish patterns from is the end goal of data visualization, and adding the right aesthetics does just that.|

3.2.1 Color

|"Color scales should be chosen to best match the data values and plot type:"|

|"This unevenness in mapping color is one reason that the multi-hued rainbow color scheme is suboptimal."|

|The excerpts above discuss the correct and incorrect ways to use color in plots. Knowing how an aesthetic like color can be detrimental is just as important as knowing how it can be beneficial. When a large portion of the population experiences something like color-blindness that affects the way they see graphs, having accessible options is important.

Open Questions and Future Research

|"One of the areas in graphics showing the most recent growth and creating the most excitement in the community is interactive graphics."|The future of the visualization may just be interactive graphics that get users more involved with data visualizations.|

|"One does not have to look far to find astonishingly bad graphics in astonishingly good outlets."|Despite research on good graphics continually coming out, bad graphics are still being published. Using incentives to push for improved graphics is a potential solution to the problem of incorrect, incomplete, and inconsistent graphs in the media.