---
title: "rhetoric"
format: html
bibliography: references.bib
---

# A Look Into Rhetorical Decisions and Arguments Made by Dr. Vanderplas, Dr. Cook, and Dr. Hoffman

When writing a paper or article of any kind, it is nearly impossible and unreasonable to keep away all outside sources and opinions, especially when the article is persuasive in nature. The author must use every shred of evidence they can to prove their point and support the opinions they put on display. The use of references, arguments, and rhetorical decisions in @vanderplas2020 are a wonderful example of how one can attempt to persuade the audience. The clear statement of arguments and opinions, liberal use of sources, and application of rhetorical decisions are big factors in the effectiveness of an study like this.

Throughout the article, the authors used concise wording to make a clear point. Under section 2.1.2.1, the authors say "One of the simplest ways to test the utility of a graph is to verify that information can be accurately read from it" [@vanderplas2020, p. 69, para. 3]. This is the first sentence of the subsection which clearly sets up what will be discussed and what the authors' stance is. There is no overly complicated jargon meant for just professionals and academics. The topic is also both specific and relevant. Another tactic implemented was the sparing use of opinions. The paper was built on facts, previous studies, and data; a strategy that's (usually) good at convincing readers to at least consider your stance.

As the authors built their arguments piece by piece, they seemed to do the same for their bibliography. Every statement, opinion, and argument made was backed up with relevant articles and/or studies. Over 100 sources were cited, many being used multiple times. In fact, as I was annotating, there were multiple places where I couldn't highlight because if I clicked on the lines they would take me directly to the references pages. This certainly isn't a bad thing though, just slightly annoying.

Finally, the use of rhetorical decisions was also important in creating effective arguments. While not employed as often as they could have, the authors used comparisons to help facilitate understanding of the topics being discussed. The biggest rhetorical device used was an analogy explicitly stated in the paper. "An analogy to conceptualize the difference is that the former is like treating plots like creatures in a zoo, with a unique name for each, while the latter is analogous to having a phylogeny based on genetic data showing how plots are related" [@vanderplas2020, p. 66, para.1]. Incorporating comparisons like these are a great way to make a difficult topic easier to understand, so I wish the authors would have done it more.

In general, the use of clear topic statements, abundant references, and rhetoric made this article easier to read, more interesting, and more persuasive. While the authors could have done more with the rhetorical devices employed, the clear and factual analysis of data visualization more than made up for it.
